# Setup
title:        Skewbed
tagline:      Because Cubing Rules
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Skewbed
  url:        https://skewbed.github.io/

tlse:
  - "R U R\' U\' R U\' R\'"
  - "R U\' R\'"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
