# Setup
title:        Skewbed
tagline:      Because Cubing Rules
baseurl:      ""
paginate:     1
future:       true

# About/contact
author:
  name:       Skewbed
  url:        https://skewbed.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

triggers:
  "{X}i": "{X}'"
  Left: Y'
  Right: Y
  
  P: "R U R'"
  P': R U' R'
  P2: R U2 R'
  
  H: U2
  T: R U R' U'
  T': U R U' R'
  
  K: R' U R
  K': R' U' R
  K2: R' U2 R
  
  S: R' F R F'
  S': F R' F' R
  L: R' U R
  
  Li: R' U' R
  U: U
  I: U'

lc-coll:
  y' (R U' R y R2 U E' R' U R U' R U' E R2 F2): "Left R I R Right R2 u L I R u' R2 F2"
  R' U R' y' R2 u' R U' R' U R' u R2 y R2: "R' U R' Left R2 u' Pi U R' u R2 Right R2"
  R U L' U2 R U' R' U2 L R U' R2: "R U L' [H] Pi [H] L R I R2"
  U2 x (R' U R U')(R' U R U')(R' U R U')(R' U R U') x': "H x (L I)4 x'"
  R2 U2 R2 U' R2 U' R2: "[R2] H [R2] I [R2] I [R2]"
  y' R2 U2 R2 U R2 U R2 y: "Left [R2] H [R2] U [R2] U [R2] Right"

zzct-beg:
  "(R U2 R') U' (R U R' U') (R U' R')": P2 I T Pi
# - R U2 [R2] U' [R2] U' [R2] U2 R
# - U (R U R' U') R U' (R' U2 R) U' (R' U2 R) U R'
# - "{(R U R') U (R U2 R')} U' {(R U2 R') U' (R U' R')}"
# - U (R U2 R') U' (R U R' U') (R U R' U') (R U' R')
# - (R U2 R') U' (R U' R')
# - (R U R') U (R U2 R')
 
# - (R U R' U') (R U R') (U R U' R')
# - (R U2 R') U2 (R U R') (U R U' R')
# - (R U2 R') U (R U2 R') U2 (R U R')
# - U' (R U2 R') U (R U R')
# - U2 (R U' R') U' (R U R' U') (R U2 R')
# - (R U2 R') U' (R U R') U (R U R')
# - U (R U R' U') (R U R') U (R U2 R') U' (R U2 R')
# - U (R U R') U2 (R U R')
# - (R U' R') U (R U R') (U R U' R')
# - U2 (R U' R') U' (R U2 R')
# - (R U R' U') (R U' R') U2 (R U2 R')
# - U' (R U' R') U2 (R U' R')
# - U' (R U' R') U (R U2 R') (U R U' R')
# - U (R U R' U') (R U2 R') U' (R U' R') U (R U R')
# - (R U2 R') U (R U R') U (R U2 R') U' (R U' R')
# - U2 (R U' R') U (R U R' U') (R U R')

oh-epll:
  - z U' R [U'] R' [U'] R' [U'] R U R U2 z'
  - R U' R U R (U R U' R') U' R2
  - R2 U2 R [U2 R2 U2 R2 U2] R U2 R2
  - "(R U R') U R' U' R' U (R U' R' U') R2 U R"
  

ohcoll:
  - R U2 R' U' R U' R2 U2' R U R' U R
  - L' U2 L U' R' U L' U' R2 U' L U R'
  - R' U R U2 L' R' U R U' L
  - U2 F R U R' U' R U' R' U' R U R' F'
  - U' r U R' U' L' U R U'
  - "U2 x' R U R' D R U' R' U' E x"

wv:
  - U2 L' U2 (R U' R') U2 L
  - (R U' R')
  - U' R' F R (U R U' R') F'
  - R2 D (R' U' R) D' R2
  - (R U' R') U (R' U' R) U' (R' U2 R)
  - U' (R U' R') U2 (R U' R') U2 (R U R')
  - (R U R' U') (R U' R')
  - (U R U' R') U (R U2 R')
  - L' U2 R U L U' L' U R' U2 L
  - R U R2 U' R2 U' R2 U2 R
  - U R' U' R2 U' R2 U2 R
  - R U' x' U R' D (R U' R') D' (x)
  - U R U2 R2 U' (R U' R') U2 R
  - U R2 D (R' U2 R) D' R2
  - U' L' (U R U' R') L
  - (U R U' R') U' R' F R (U R U' R') F'
  - U (R U2 R')
  - U' R' F' R U2 (R U2 R') F
  - U L' (U R U' R') L U' (R U' R')

tlse:
  - (U R U' R') U' (R U' R') (U R U' R')
  - (R U' R')
  - U' (R U2 R') U2 (R U2 R')
  - R2 D R' U' R D' R2
  - (R U' R') U R' U' (R U' R') U2 R
  - (R U R') U2 (R U' R') U' (R U R')
  - (R U R' U') (R U' R')
  - (U R U' R') U (R U2 R')
  - U2 (R U2 R') U (R U2 R')
  - U' (R U' R') U (R U R' U') (R U' R')
  - (R U' R') U' (R U2 R') U' (R U' R')
  - (R U R') U2 (R U2 R') (U R U' R')
  - U' (R U' R') (U R U' R')
  - U' (R U R') U2 (R U2 R')
  - U' L' (U R U' R') L
  - (R U2 R') (U R U' R') (U R U' R')
  - U (R U2 R')
  - U' (R U2 R') (U R U' R')
  - U' (R U R' U') (R U R')
  - (R U' R') U' (R U R') U (R U2 R')
  - (R U' R') U (R U R') U (R U2 R')
  - R U R D R' U2 R D' R2
  - (U R U' R') (U R U' R') U (R U2 R')
  - U2 (R U R' U') (R U R') U2 (R U R')
  - U2 (R U R' U') (R U R') U2 (R U R')
  - (R U' R') U (R U2 R') U' (R U' R')
  - (R U R' U') (R U R' U') (R U' R')
  - (U R U' R') U2 (R U R')
  - U' (R U R') (U R U' R')
  - U' L U' (R U R') L'
  - (U R U' R') U' (R U R') (U R U' R')
  - U2 (R U R' U') (R U' R') U2 (R U' R')
  - R' U2 (R U R') U R U' (R U R')
  - R' D' r U2 r' D R
  - (R U' R') U' (R U R') U2 (R U R')
  - U (R U2 R') U2 (R U R') U2 (R U R')
  - (R U R') (U R U' R') U' (R U' R')
  - (R U' R') U (R U2 R') U' (R U R') U (R U R')
  - U2 (R U' R') U2 (R U R') (U R U' R')
  - (R U R') U2 (R U R') (U R U' R')
  - U2 F' (R U R' U') R' F R
  - U2 (R U R')
  - (U R U' R') (U R U' R') U2 (R U R')
  - U' (R U R' U') (R U' R') U (R U R')
  - (R U2 R') U' (R U R') U2 (R U' R')
  - (R U' R') U2 (R U R') U2 (R U R')
  - (R U' R') U (R U R') U2 (R U R')
  - U' (R U R') U (R U2 R') U' (R U2 R')
  - U (R U R' U') (R U R') U2 (R U' R')
  - U R U R D R' U2 R D' R' U' R'
  - U R' U' (R U' R') U2 R U' (R U R')
  - (R U2 R') U' (R U R' U') (R U2 R')
  - (R U R') U (R U R')
  - U (R U R' U') (R U R' U') (R U2 R')
  - (R U R' U') (R U2 R') U' (R U2 R')
  - (R U2 R') U (R U R') (U R U' R')
  - U' (R U' R') U2 (R U2 R')
  - (R U2 R') U (R U2 R') (U R U' R')
  - (U R U' R') U (R U R') U2 (R U' R')
  - U' (R U R') U2 (R U' R') U (R U2 R')
  - (R U' R') U' (R U' R') U2 (R U' R')
  - U (R U2 R') U' (R U' R') U' (R U2 R')
  - (R U R') (U R U' R') U (R U R')
  - (R U' R') U2 (R U' R') U2 (R U' R')
  - U' (R U2 R') U' (R U2 R') U2 (R U R')
  - U (R U R') U2 (R U' R')
  - U R' U2 (R U R') U R2 U' R'
  - U2 (R U' R') U (R U R')
  - U' (R U' R') U (R U2 R') U' (R U2 R')
  - (R U' R') U' (R U' R') U' (R U2 R')
  - (R U2 R') U' (R U2 R')
  - R U2 R D R' U R D' R2
  - (R U' R') (U R U' R') U2 (R U' R')
  - U (R U R') U (R U2 R') (U R U' R')
  - U (R U R' U') (R U2 R')
  - (R U2 R') U2 (R U' R')
  - U R U R D R' U R D' R2
  - (U R U' R') U (R U R' U') (R U2 R')
  - U' (R U2 R') U' (R U' R') U (R U R')
  - U2 R' U2 (R U R') U R U' (R U2 R')
  - U2 (R U R' U') (R U2 R') U' (R U' R')
