# Setup
title:        Skewbed
tagline:      Because Cubing Rules
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Skewbed
  url:        https://skewbed.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

wv:
  - U2 L' U2 (R U' R') U2 L
  - (R U' R')
  - U' R' F R (U R U' R') F'
  - R2 D (R' U' R) D' R2
  - (R U' R') U (R' U' R) U' (R' U2 R)
  - U' (R U' R') U2 (R U' R') U2 (R U R')
  - (R U R' U') (R U' R')
  - (U R U' R') U (R U2 R')
  - L' U2 R U L U' L' U R' U2 L
  - R U R2 U' R2 U' R2 U2 R
  - U R' U' R2 U' R2 U2 R
  - R U' x' U R' D (R U' R') D' (x)
  - U R U2 R2 U' (R U' R') U2 R
  - U R2 D (R' U2 R) D' R2
  - U' L' (U R U' R') L
  - (U R U' R') U' R' F R (U R U' R') F'
  - U (R U2 R')
  - U' R' F' R U2 (R U2 R') F
  - U L' (U R U' R') L U' (R U' R')

tlse:
  - U (R U' R') U' (R U' R') U (R U' R')
  - (R U' R')
  - U' (R U2 R') U2 (R U2 R')
  - R2 D R' U' R D' R2
  - (R U' R') U R' U' (R U' R') U2 R
  - (R U R') U2 (R U' R') U' (R U R')
  - (R U R' U') (R U' R')
  - U (R U' R') U (R U2 R')
  - U2 (R U2 R') U (R U2 R')
  - U' (R U' R') U (R U R' U') (R U' R')
  - (R U' R') U' (R U2 R') U' (R U' R')
  - (R U R') U2 (R U2 R') U (R U' R')
  - U' (R U' R') U (R U' R')
  - U' (R U R') U2 (R U2 R')
  - U' L' U (R U' R') L
  - (R U2 R') U (R U' R') U (R U' R')
  - U (R U2 R')
  - U' (R U2 R') U (R U' R')
  - U' (R U R' U') (R U R')
  - (R U' R') U' (R U R') U (R U2 R')
  - (R U' R') U (R U R') U (R U2 R')
  - R U R D R' U2 R D' R2
  - U (R U' R') U (R U' R') U (R U2 R')
  - U2 (R U R' U') (R U R') U2 (R U R')
  - U2 (R U R' U') (R U R') U2 (R U R')
  - (R U' R') U (R U2 R') U' (R U' R')
  - (R U R' U') (R U R' U') (R U' R')
  - U (R U' R') U2 (R U R')
  - U' (R U R') U (R U' R')
  - U' L U' (R U R') L'
  - U (R U' R') U' (R U R') U (R U' R')
  - U2 (R U R' U') (R U' R') U2 (R U' R')
  - R' U2 (R U R') U R U' (R U R')
  - R' D' r U2 r' D R
  - (R U' R') U' (R U R') U2 (R U R')
  - U (R U2 R') U2 (R U R') U2 (R U R')
  - (R U R') U (R U' R') U' (R U' R')
  - (R U' R') U (R U2 R') U' (R U R') U (R U R')
  - U2 (R U' R') U2 (R U R') U (R U' R')
  - (R U R') U2 (R U R') U (R U' R')
  - U2 F' (R U R' U') R' F R
  - U2 (R U R')
  - U (R U' R') U (R U' R') U2 (R U R')
  - U' (R U R' U') (R U' R') U (R U R')
  - (R U2 R') U' (R U R') U2 (R U' R')
  - (R U' R') U2 (R U R') U2 (R U R')
  - (R U' R') U (R U R') U2 (R U R')
  - U' (R U R') U (R U2 R') U' (R U2 R')
  - U (R U R' U') (R U R') U2 (R U' R')
  - U R U R D R' U2 R D' R' U' R'
  - U R' U' (R U' R') U2 R U' (R U R')
  - (R U2 R') U' (R U R' U') (R U2 R')
  - (R U R') U (R U R')
  - U (R U R' U') (R U R' U') (R U2 R')
  - (R U R' U') (R U2 R') U' (R U2 R')
  - (R U2 R') U (R U R') U (R U' R')
  - U' (R U' R') U2 (R U2 R')
  - (R U2 R') U (R U2 R') U (R U' R')
  - U (R U' R') U (R U R') U2 (R U' R')
  - U' (R U R') U2 (R U' R') U (R U2 R')
  - (R U' R') U' (R U' R') U2 (R U' R')
  - U (R U2 R') U' (R U' R') U' (R U2 R')
  - (R U R') U (R U' R') U (R U R')
  - (R U' R') U2 (R U' R') U2 (R U' R')
  - U' (R U2 R') U' (R U2 R') U2 (R U R')
  - U (R U R') U2 (R U' R')
  - U R' U2 (R U R') U R2 U' R'
  - U2 (R U' R') U (R U R')
  - U' (R U' R') U (R U2 R') U' (R U2 R')
  - (R U' R') U' (R U' R') U' (R U2 R')
  - (R U2 R') U' (R U2 R')
  - R U2 R D R' U R D' R2
  - (R U' R') U (R U' R') U2 (R U' R')
  - U (R U R') U (R U2 R') U (R U' R')
  - U (R U R' U') (R U2 R')
  - (R U2 R') U2 (R U' R')
  - U R U R D R' U R D' R2
  - U (R U' R') U (R U R' U') (R U2 R')
  - U' (R U2 R') U' (R U' R') U (R U R')
  - U2 R' U2 (R U R') U R U' (R U2 R')
  - U2 (R U R' U') (R U2 R') U' (R U' R')
